name: backend-php-technical-test

services:
    php:
        build: .
        volumes:
            - ./app:/code
        working_dir: /code

    redis:
        image: redis:7.2.3-alpine
        ports:
            - '6379:6379'
        volumes:
            - ./data/redis:/data
        command: ["redis-server", "--requirepass", "password"]

    nginx:
        image: nginx:1.25.0-bullseye
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./app:/code
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
