name: backend-php-technical-test

services:
    php:
        build: .
        volumes:
            - ./app:/code
        working_dir: /code

    nginx:
        image: nginx:1.25.0-bullseye
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./app:/code
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
